### PR TITLE
CI memory bug test

### PR DESCRIPTION
**Pull request by seanyoung**
Signed-off-by: Sean Young <sean@mess.org>

### CODE REVIEW

**Comment by seanyoung** [comment]
[clabot:check]

**Comment by TriplEight** [comment]
bors try

**Comment by seanyoung** [comment]
bors try

**Comment by TriplEight** [comment]
@seanyoung I've disabled bors for the project. Unfortunately, it's incompatible with pushes from forks.
Here's your pipeline from the latest commit https://gitlab.parity.io/parity/pallet-contracts-waterfall/pipelines/94481

**Pull request closed without merging**
