### PR TITLE
Solang Flipper test fixed

### PR DESCRIPTION
**Pull request by kirillt**
The failing test is fixed now.
The reason why it was failing is wrong selector used. There was a bug with Solang accepting any value as a selector, so the wrong selector was not detected before and the bug fix broke the test case.

### CODE REVIEW

**Comment by Stefie** [comment]
To my knowledge that's not a bug, the selector can have any value. @pepyakin can for sure specify that.

The goal is to get the value directly from the generated metadata.json file and to not have it hardcoded in the tests (if available).

The AssemblyScript and the Raw Rust contracts don't have automatically generated metadata, that's why it's correct that the value is hardcoded in these tests.

For ink! it should use the contracts metadata file, but because there is currently a re-write going on and the function that should be used for it from the JS API is knowingly not working 100%  right now, I copied it over manually.

The Solang tests should also use the value from the metadata, not a hardcoded one, once the metadata refactor is finished.

**Comment by Stefie** [comment]
Also... the CI tests are still failing?

**Comment by kirillt** [comment]
You are right, the selector value should be taken from metadata. But I suggest to approve this PR just to make CI green again, and I will make test suite use metadata instead of hardcoded value in separate PR.

About is it a bug or not -- this was a bug in Solang, not pallet-contracts. Due to some LLVM optimisations selector was not used there at all, leading to availability to use any value with the same (successful) effect.

**Comment by Stefie** [comment]
I'm totally fine with merging, but the CI is still failing
https://gitlab.parity.io/parity/pallet-contracts-waterfall/-/jobs/444618

**Comment by Stefie** [comment]
Closing in favour of https://github.com/paritytech/pallet-contracts-waterfall/pull/75

**Pull request closed without merging**
