### PR TITLE
CI memory bug

### LINKED ISSUE #77: CI broken for Solang test
The CI is throwing an error:
`FATAL ERROR: MarkCompactCollector: semi-space copy, fallback in old gen Allocation failed - JavaScript heap out of memory`

Additional Info:
- All tests are passing locally (with the latest versions)
- Test are passing in the CI, if I'm commenting out the one Solang test
- Cause of the error is the Solang setup in the CI
- The problem has been around for a while, so it's no new behaviour related to any recent changes

I'm pretty sure it has something to do with the node configuration on Gitlab https://devcenter.heroku.com/articles/node-memory-use

### PR DESCRIPTION
**Pull request by Stefie**
To investigate/ fix https://github.com/paritytech/pallet-contracts-waterfall/issues/77

### CODE REVIEW

**Comment by TriplEight** [comment]
bors try

**Comment by TriplEight** [comment]
bors try

**Comment by TriplEight** [comment]
bors try-

**Comment by TriplEight** [comment]
bors try

**Comment by TriplEight** [comment]
bors try-

**Comment by TriplEight** [comment]
bors try

**Comment by Stefie** [comment]
Fixed by updating Solang version in CI

**Pull request closed without merging**
