### PR TITLE
Updated tests to new ext_set_storage implementation

### PR DESCRIPTION
**Pull request by Stefie**
Implements changes from https://github.com/paritytech/substrate/pull/5103

I updated the raw Rust and AssemblyScript tests.

The Solang test is still failing, that means that an old version of Solang is pulled in somewhere.
Could you have a look at this @kirillt and fix it in a separate PR?

@seunlanlege merged the PR in Solang 5 days ago: https://github.com/hyperledger-labs/solang/pull/141

### CODE REVIEW

**Comment by seunlanlege** [comment]
:sweat_smile:,  Looks like parallel universes have merged and I have a doppelganger running around merging PRs in hyperledger.

**Comment by seunlanlege** [comment]
oh wait you meant to tag @seanyoung

**Review by TriplEight — APPROVED** [review]
LGTM

**Comment by Stefie** [comment]
> oh wait you meant to tag @seanyoung

Exactly, damned, sorry @seunlanlege 😄 !  It seems I hit enter too fast, you were the first suggestion that popped up

**Pull request merged**
